---
- name: User SSH Configuration with key based auth
  hosts: preprod
  remote_user: admk
  become: true

  vars_files:
    - vars/secrets.yml # Load encrypted variables (e.g., ssh_password)


  roles:
    - user_ssh_conf
